# Generated by Django 4.2 on 2025-01-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('director_name', models.CharField(max_length=255)),
                ('release_year', models.IntegerField()),
                ('synopsis', models.TextField()),
            ],
        ),
    ]
